// Generated by astgen // -*- mode: C++; c-file-style: "cc-mode" -*-
#define ASTGEN_MEMBERS_DfgAdd \
    static constexpr VDfgType dfgType() { return VDfgType::Add; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgAnd \
    static constexpr VDfgType dfgType() { return VDfgType::And; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgArraySel \
    static constexpr VDfgType dfgType() { return VDfgType::ArraySel; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* fromp() const { return inputp(0); } \
    void fromp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* bitp() const { return inputp(1); } \
    void bitp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "fromp", "bitp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgBufIf1 \
    static constexpr VDfgType dfgType() { return VDfgType::BufIf1; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgConcat \
    static constexpr VDfgType dfgType() { return VDfgType::Concat; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgCond \
    static constexpr VDfgType dfgType() { return VDfgType::Cond; }; \
    using Super = DfgVertexTernary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* condp() const { return inputp(0); } \
    void condp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* thenp() const { return inputp(1); } \
    void thenp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    DfgVertex* elsep() const { return inputp(2); } \
    void elsep(DfgVertex* vtxp) { inputp(2, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[3] = { "condp", "thenp", "elsep" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgConst \
    static constexpr VDfgType dfgType() { return VDfgType::Const; }; \
    using Super = DfgVertexNullary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgDiv \
    static constexpr VDfgType dfgType() { return VDfgType::Div; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgDivS \
    static constexpr VDfgType dfgType() { return VDfgType::DivS; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgEq \
    static constexpr VDfgType dfgType() { return VDfgType::Eq; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgEqCase \
    static constexpr VDfgType dfgType() { return VDfgType::EqCase; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgEqWild \
    static constexpr VDfgType dfgType() { return VDfgType::EqWild; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgExtend \
    static constexpr VDfgType dfgType() { return VDfgType::Extend; }; \
    using Super = DfgVertexUnary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgExtendS \
    static constexpr VDfgType dfgType() { return VDfgType::ExtendS; }; \
    using Super = DfgVertexUnary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgGt \
    static constexpr VDfgType dfgType() { return VDfgType::Gt; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgGtS \
    static constexpr VDfgType dfgType() { return VDfgType::GtS; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgGte \
    static constexpr VDfgType dfgType() { return VDfgType::Gte; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgGteS \
    static constexpr VDfgType dfgType() { return VDfgType::GteS; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgLogAnd \
    static constexpr VDfgType dfgType() { return VDfgType::LogAnd; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgLogEq \
    static constexpr VDfgType dfgType() { return VDfgType::LogEq; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgLogIf \
    static constexpr VDfgType dfgType() { return VDfgType::LogIf; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgLogNot \
    static constexpr VDfgType dfgType() { return VDfgType::LogNot; }; \
    using Super = DfgVertexUnary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgLogOr \
    static constexpr VDfgType dfgType() { return VDfgType::LogOr; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgLogic \
    static constexpr VDfgType dfgType() { return VDfgType::Logic; }; \
    using Super = DfgVertexVariadic; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgLt \
    static constexpr VDfgType dfgType() { return VDfgType::Lt; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgLtS \
    static constexpr VDfgType dfgType() { return VDfgType::LtS; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgLte \
    static constexpr VDfgType dfgType() { return VDfgType::Lte; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgLteS \
    static constexpr VDfgType dfgType() { return VDfgType::LteS; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgModDiv \
    static constexpr VDfgType dfgType() { return VDfgType::ModDiv; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgModDivS \
    static constexpr VDfgType dfgType() { return VDfgType::ModDivS; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgMul \
    static constexpr VDfgType dfgType() { return VDfgType::Mul; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgMulS \
    static constexpr VDfgType dfgType() { return VDfgType::MulS; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgMux \
    static constexpr VDfgType dfgType() { return VDfgType::Mux; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgNegate \
    static constexpr VDfgType dfgType() { return VDfgType::Negate; }; \
    using Super = DfgVertexUnary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgNeq \
    static constexpr VDfgType dfgType() { return VDfgType::Neq; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgNeqCase \
    static constexpr VDfgType dfgType() { return VDfgType::NeqCase; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgNeqWild \
    static constexpr VDfgType dfgType() { return VDfgType::NeqWild; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgNot \
    static constexpr VDfgType dfgType() { return VDfgType::Not; }; \
    using Super = DfgVertexUnary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgOr \
    static constexpr VDfgType dfgType() { return VDfgType::Or; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgPow \
    static constexpr VDfgType dfgType() { return VDfgType::Pow; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgPowSS \
    static constexpr VDfgType dfgType() { return VDfgType::PowSS; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgPowSU \
    static constexpr VDfgType dfgType() { return VDfgType::PowSU; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgPowUS \
    static constexpr VDfgType dfgType() { return VDfgType::PowUS; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgRedAnd \
    static constexpr VDfgType dfgType() { return VDfgType::RedAnd; }; \
    using Super = DfgVertexUnary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgRedOr \
    static constexpr VDfgType dfgType() { return VDfgType::RedOr; }; \
    using Super = DfgVertexUnary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgRedXor \
    static constexpr VDfgType dfgType() { return VDfgType::RedXor; }; \
    using Super = DfgVertexUnary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgReplicate \
    static constexpr VDfgType dfgType() { return VDfgType::Replicate; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* srcp() const { return inputp(0); } \
    void srcp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* countp() const { return inputp(1); } \
    void countp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "srcp", "countp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgSel \
    static constexpr VDfgType dfgType() { return VDfgType::Sel; }; \
    using Super = DfgVertexUnary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgShiftL \
    static constexpr VDfgType dfgType() { return VDfgType::ShiftL; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgShiftR \
    static constexpr VDfgType dfgType() { return VDfgType::ShiftR; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgShiftRS \
    static constexpr VDfgType dfgType() { return VDfgType::ShiftRS; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgSpliceArray \
    static constexpr VDfgType dfgType() { return VDfgType::SpliceArray; }; \
    using Super = DfgVertexSplice; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgSplicePacked \
    static constexpr VDfgType dfgType() { return VDfgType::SplicePacked; }; \
    using Super = DfgVertexSplice; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgStreamL \
    static constexpr VDfgType dfgType() { return VDfgType::StreamL; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgStreamR \
    static constexpr VDfgType dfgType() { return VDfgType::StreamR; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgSub \
    static constexpr VDfgType dfgType() { return VDfgType::Sub; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgUnitArray \
    static constexpr VDfgType dfgType() { return VDfgType::UnitArray; }; \
    using Super = DfgVertexUnary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgUnresolved \
    static constexpr VDfgType dfgType() { return VDfgType::Unresolved; }; \
    using Super = DfgVertexVariadic; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgVarArray \
    static constexpr VDfgType dfgType() { return VDfgType::VarArray; }; \
    using Super = DfgVertexVar; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgVarPacked \
    static constexpr VDfgType dfgType() { return VDfgType::VarPacked; }; \
    using Super = DfgVertexVar; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgVertexBinary \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgVertexNullary \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgVertexSplice \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgVertexTernary \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgVertexUnary \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgVertexVar \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgVertexVariadic \
    static_assert(true, "")
#define ASTGEN_MEMBERS_DfgXor \
    static constexpr VDfgType dfgType() { return VDfgType::Xor; }; \
    using Super = DfgVertexBinary; \
    void accept(DfgVisitor& v) override { v.visit(this); } \
    DfgVertex* lhsp() const { return inputp(0); } \
    void lhsp(DfgVertex* vtxp) { inputp(0, vtxp); } \
    DfgVertex* rhsp() const { return inputp(1); } \
    void rhsp(DfgVertex* vtxp) { inputp(1, vtxp); } \
    std::string srcName(size_t idx) const override final { \
        static const char* names[2] = { "lhsp", "rhsp" }; \
        return names[idx]; \
    } \
    static_assert(true, "")
