// Generated by astgen // -*- mode: C++; c-file-style: "cc-mode" -*-
class DfgAdd;              // DfgVertex       DfgVertexBinary 
class DfgAnd;              // DfgVertex       DfgVertexBinary 
class DfgArraySel;         // DfgVertex       DfgVertexBinary 
class DfgBufIf1;           // DfgVertex       DfgVertexBinary 
class DfgConcat;           // DfgVertex       DfgVertexBinary 
class DfgCond;             // DfgVertex       DfgVertexTernary 
class DfgConst;            // DfgVertex       DfgVertexNullary 
class DfgDiv;              // DfgVertex       DfgVertexBinary 
class DfgDivS;             // DfgVertex       DfgVertexBinary 
class DfgEq;               // DfgVertex       DfgVertexBinary 
class DfgEqCase;           // DfgVertex       DfgVertexBinary 
class DfgEqWild;           // DfgVertex       DfgVertexBinary 
class DfgExtend;           // DfgVertex       DfgVertexUnary  
class DfgExtendS;          // DfgVertex       DfgVertexUnary  
class DfgGt;               // DfgVertex       DfgVertexBinary 
class DfgGtS;              // DfgVertex       DfgVertexBinary 
class DfgGte;              // DfgVertex       DfgVertexBinary 
class DfgGteS;             // DfgVertex       DfgVertexBinary 
class DfgLogAnd;           // DfgVertex       DfgVertexBinary 
class DfgLogEq;            // DfgVertex       DfgVertexBinary 
class DfgLogIf;            // DfgVertex       DfgVertexBinary 
class DfgLogNot;           // DfgVertex       DfgVertexUnary  
class DfgLogOr;            // DfgVertex       DfgVertexBinary 
class DfgLogic;            // DfgVertex       DfgVertexVariadic 
class DfgLt;               // DfgVertex       DfgVertexBinary 
class DfgLtS;              // DfgVertex       DfgVertexBinary 
class DfgLte;              // DfgVertex       DfgVertexBinary 
class DfgLteS;             // DfgVertex       DfgVertexBinary 
class DfgModDiv;           // DfgVertex       DfgVertexBinary 
class DfgModDivS;          // DfgVertex       DfgVertexBinary 
class DfgMul;              // DfgVertex       DfgVertexBinary 
class DfgMulS;             // DfgVertex       DfgVertexBinary 
class DfgMux;              // DfgVertex       DfgVertexBinary 
class DfgNegate;           // DfgVertex       DfgVertexUnary  
class DfgNeq;              // DfgVertex       DfgVertexBinary 
class DfgNeqCase;          // DfgVertex       DfgVertexBinary 
class DfgNeqWild;          // DfgVertex       DfgVertexBinary 
class DfgNot;              // DfgVertex       DfgVertexUnary  
class DfgOr;               // DfgVertex       DfgVertexBinary 
class DfgPow;              // DfgVertex       DfgVertexBinary 
class DfgPowSS;            // DfgVertex       DfgVertexBinary 
class DfgPowSU;            // DfgVertex       DfgVertexBinary 
class DfgPowUS;            // DfgVertex       DfgVertexBinary 
class DfgRedAnd;           // DfgVertex       DfgVertexUnary  
class DfgRedOr;            // DfgVertex       DfgVertexUnary  
class DfgRedXor;           // DfgVertex       DfgVertexUnary  
class DfgReplicate;        // DfgVertex       DfgVertexBinary 
class DfgSel;              // DfgVertex       DfgVertexUnary  
class DfgShiftL;           // DfgVertex       DfgVertexBinary 
class DfgShiftR;           // DfgVertex       DfgVertexBinary 
class DfgShiftRS;          // DfgVertex       DfgVertexBinary 
class DfgSpliceArray;      // DfgVertex       DfgVertexVariadic DfgVertexSplice 
class DfgSplicePacked;     // DfgVertex       DfgVertexVariadic DfgVertexSplice 
class DfgStreamL;          // DfgVertex       DfgVertexBinary 
class DfgStreamR;          // DfgVertex       DfgVertexBinary 
class DfgSub;              // DfgVertex       DfgVertexBinary 
class DfgUnitArray;        // DfgVertex       DfgVertexUnary  
class DfgUnresolved;       // DfgVertex       DfgVertexVariadic 
class DfgVarArray;         // DfgVertex       DfgVertexVar    
class DfgVarPacked;        // DfgVertex       DfgVertexVar    
class DfgVertex;           // 
class DfgVertexBinary;     // DfgVertex       
class DfgVertexNullary;    // DfgVertex       
class DfgVertexSplice;     // DfgVertex       DfgVertexVariadic 
class DfgVertexTernary;    // DfgVertex       
class DfgVertexUnary;      // DfgVertex       
class DfgVertexVar;        // DfgVertex       
class DfgVertexVariadic;   // DfgVertex       
class DfgXor;              // DfgVertex       DfgVertexBinary 
